const express = require('express');
const router = express.Router();
const { supabase } = require('../db/db');
const { addUserToRequest, requireAuth, isSuperAdmin } = require('../middleware/authMiddleware');

const filterCache = {
  locations: { data: null, timestamp: 0, ttl: 5 * 60 * 1000 },
  sectors: { data: null, timestamp: 0, ttl: 5 * 60 * 1000 },
  companies: { data: null, timestamp: 0, ttl: 5 * 60 * 1000 },
  externalIds: { data: null, timestamp: 0, ttl: 10 * 60 * 1000 }
};

const STATUS_TO_ID = { active: 1, paused: 2, archived: 3, draft: 4, expired: 5 };
const ID_TO_STATUS = { 1: 'active', 2: 'paused', 3: 'archived', 4: 'draft', 5: 'expired' };
const ACTIVE_STATUSES = new Set(['active']);

function getCache(key) {
  const cached = filterCache[key];
  if (cached?.data && Date.now() - cached.timestamp < cached.ttl) return cached.data;
  return null;
}

function setCache(key, data) {
  filterCache[key].data = data;
  filterCache[key].timestamp = Date.now();
}

function hasActiveFilterValues(filters) {
  return Object.values(filters).some(value => Array.isArray(value) ? value.length > 0 : Boolean(value));
}

function normalizeStatus(value) {
  if (!value || value === 'all') return null;
  if (typeof value === 'number') return ID_TO_STATUS[value] || null;
  const raw = String(value).toLowerCase();
  if (ID_TO_STATUS[Number(raw)]) return ID_TO_STATUS[Number(raw)];
  if (STATUS_TO_ID[raw]) return raw;
  if (raw === 'pending') return 'draft';
  return null;
}

function statusId(status) {
  return STATUS_TO_ID[normalizeStatus(status) || 'draft'] || 4;
}

function formatSalary(min, max, raw) {
  if (raw) return raw;
  if (min && max && min > 0 && max > 0) return `${Math.round(min).toLocaleString('es')}-${Math.round(max).toLocaleString('es')}€`;
  if (min && min > 0) return `Desde ${Math.round(min).toLocaleString('es')}€`;
  if (max && max > 0) return `Hasta ${Math.round(max).toLocaleString('es')}€`;
  return 'No especificado';
}

function formatLocation(city, region) {
  if (city && region && region.trim()) return `${city}, ${region}`;
  return city || region || null;
}

function sanitizePostgrestOrTerm(value) {
  return String(value || '')
    .trim()
    // Commas and parentheses are control characters inside PostgREST `.or(...)`.
    .replace(/[(),]/g, ' ')
    .replace(/\s+/g, ' ');
}

function parseLocationValue(value) {
  const raw = String(value || '').trim();
  if (!raw) return { city: null, region: null, term: null };

  const parts = raw
    .split(',')
    .map(part => part.trim())
    .filter(Boolean);
  const parsedCity = sanitizePostgrestOrTerm(parts[0]) || null;
  const parsedRegion = sanitizePostgrestOrTerm(parts[parts.length - 1]) || null;

  return {
    city: parsedCity,
    region: parts.length > 1 ? parsedRegion : null,
    term: sanitizePostgrestOrTerm(raw)
  };
}

function normalizeLocationFilter(value) {
  if (!value) return [];
  const values = Array.isArray(value) ? value : [value];
  return values
    .flatMap(item => String(item || '').split('|'))
    .map(item => item.trim())
    .filter(item => item && item !== 'all');
}

function normalizeStringFilter(value) {
  if (!value) return [];
  const values = Array.isArray(value) ? value : [value];
  return values
    .flatMap(item => String(item || '').split('|'))
    .map(item => item.trim())
    .filter(item => item && item !== 'all');
}

function applyMultiOrFilter(query, values, fields) {
  const terms = normalizeStringFilter(values)
    .slice(0, 25)
    .map(sanitizePostgrestOrTerm)
    .filter(Boolean);
  if (terms.length === 0) return query;

  const parts = [];
  terms.forEach(term => {
    fields.forEach(field => parts.push(`${field}.ilike.%${term}%`));
  });

  return parts.length > 0 ? query.or(parts.join(',')) : query;
}

function applyLocationFilter(query, location) {
  const locations = normalizeLocationFilter(location);
  if (locations.length === 0) return query;

  const parts = [];
  locations.slice(0, 25).forEach(item => {
    const parsed = parseLocationValue(item);
    if (!parsed.term) return;

    // Values generated by /job-offers/locations use "City, Region".
    // For imported feeds we can receive "City, City, Province"; matching the
    // first part as city and the last part as broad region keeps the filter
    // stable without relying on exact source formatting.
    if (parsed.city && parsed.region) {
      parts.push(`and(City.ilike.%${parsed.city}%,Region.ilike.%${parsed.region}%)`);
      return;
    }

    parts.push(`City.ilike.%${parsed.term}%`);
    parts.push(`Region.ilike.%${parsed.term}%`);
    parts.push(`Country.ilike.%${parsed.term}%`);
    parts.push(`CountryCode.ilike.%${parsed.term}%`);
  });

  return parts.length > 0 ? query.or(parts.join(',')) : query;
}

function applyUserFilter(query, req) {
  return isSuperAdmin(req) ? query : query.eq('UserId', req.userId);
}

function mapOffer(row) {
  const status = normalizeStatus(row.Status) || 'draft';
  return {
    id: row.Id,
    Id: row.Id,
    OfferId: row.Id, // shim: old frontend/components sometimes still use OfferId
    ExternalId: row.ExternalId,
    title: row.Title,
    Title: row.Title,
    description: row.DescriptionText || row.DescriptionHtml,
    Description: row.DescriptionText || row.DescriptionHtml,
    company: row.CompanyName,
    CompanyName: row.CompanyName,
    sector: row.Sector || row.Category,
    Sector: row.Sector || row.Category,
    City: row.City,
    Region: row.Region,
    location: formatLocation(row.City, row.Region),
    SalaryMin: row.SalaryMin,
    SalaryMax: row.SalaryMax,
    SalaryRaw: row.SalaryRaw,
    salary: formatSalary(row.SalaryMin, row.SalaryMax, row.SalaryRaw),
    type: row.JobType || row.ContractType || 'No especificado',
    JobType: row.JobType,
    publishDate: row.PublicationDate,
    PublicationDate: row.PublicationDate,
    CreatedAt: row.CreatedAt,
    Status: status,
    StatusId: statusId(status),
    status,
    campaignCount: 0,
    segmentCount: 0,
    promotion: 'Sin campañas',
    campaigns: null,
    segments: null,
    totalBudget: 0,
    budgetSpent: 0,
    targetApplications: 0,
    applicationsReceived: 0,
    performance: 'Sin datos'
  };
}

function emptyState(page, limit, filters) {
  return {
    success: true,
    data: [],
    items: [],
    hasMore: false,
    total: 0,
    next: null,
    pagination: { page, limit, total: 0, pages: 0, hasMore: false, lastCreatedAt: null, lastId: null },
    stats: { totalOffers: 0, activeOffers: 0, pendingOffers: 0, pausedOffers: 0, totalSectors: 0, totalCities: 0 },
    filters
  };
}

function applyOfferFilters(query, req, filters) {
  query = applyUserFilter(query, req);
  if (filters.status) query = query.eq('Status', filters.status);
  query = applyLocationFilter(query, filters.locations || filters.location);
  query = applyMultiOrFilter(query, filters.sectors || filters.sector, ['Sector', 'Category']);
  query = applyMultiOrFilter(query, filters.companies || filters.company, ['CompanyName']);
  query = applyMultiOrFilter(query, filters.jobTitles || filters.titles, ['Title', 'CompanyName']);
  if (filters.externalId) query = query.ilike('ExternalId', `%${filters.externalId}%`);
  if (filters.search) {
    const term = sanitizePostgrestOrTerm(filters.search);
    query = query.or(`Title.ilike.%${term}%,CompanyName.ilike.%${term}%,Sector.ilike.%${term}%,Category.ilike.%${term}%,City.ilike.%${term}%,Region.ilike.%${term}%,Country.ilike.%${term}%`);
  }
  return query;
}

router.get('/job-offers/locations', addUserToRequest, requireAuth, async (req, res) => {
  try {
    const filters = {
      status: normalizeStatus(req.query.status),
      sectors: normalizeStringFilter(req.query.sector),
      companies: normalizeStringFilter(req.query.company),
      jobTitles: normalizeStringFilter(req.query.jobTitle || req.query.jobTitles),
      externalId: req.query.externalId && req.query.externalId !== 'all' ? String(req.query.externalId).trim() : null,
      search: req.query.q?.trim() || null
    };
    const hasFilters = hasActiveFilterValues(filters);
    if (!hasFilters) {
      const cached = getCache('locations');
      if (cached) return res.json({ success: true, data: cached });
    }
    let query = supabase.from('JobOffers').select('City, Region').or('City.not.is.null,Region.not.is.null');
    query = applyOfferFilters(query, req, filters);
    const { data, error } = await query;
    if (error) throw error;
    const locations = [...new Set((data || []).map(r => formatLocation(r.City, r.Region)).filter(Boolean))].sort();
    if (!hasFilters) setCache('locations', locations);
    res.json({ success: true, data: locations });
  } catch (error) {
    res.status(500).json({ success: false, error: 'Error interno del servidor', details: error.message });
  }
});

router.get('/job-offers/sectors', addUserToRequest, requireAuth, async (req, res) => {
  try {
    const filters = {
      status: normalizeStatus(req.query.status),
      locations: normalizeLocationFilter(req.query.location),
      companies: normalizeStringFilter(req.query.company),
      jobTitles: normalizeStringFilter(req.query.jobTitle || req.query.jobTitles),
      externalId: req.query.externalId && req.query.externalId !== 'all' ? String(req.query.externalId).trim() : null,
      search: req.query.q?.trim() || null
    };
    const hasFilters = hasActiveFilterValues(filters);
    if (!hasFilters) {
      const cached = getCache('sectors');
      if (cached) return res.json({ success: true, data: cached });
    }
    let query = supabase.from('JobOffers').select('Sector, Category').or('Sector.not.is.null,Category.not.is.null');
    query = applyOfferFilters(query, req, filters);
    const { data, error } = await query;
    if (error) throw error;
    const sectors = [...new Set((data || []).flatMap(r => [r.Sector, r.Category]).filter(Boolean))].sort();
    if (!hasFilters) setCache('sectors', sectors);
    res.json({ success: true, data: sectors });
  } catch (error) {
    res.status(500).json({ success: false, error: 'Error interno del servidor', details: error.message });
  }
});

router.get('/job-offers/external-ids', addUserToRequest, requireAuth, async (req, res) => {
  try {
    const filters = {
      status: normalizeStatus(req.query.status),
      locations: normalizeLocationFilter(req.query.location),
      sectors: normalizeStringFilter(req.query.sector),
      companies: normalizeStringFilter(req.query.company),
      jobTitles: normalizeStringFilter(req.query.jobTitle || req.query.jobTitles),
      search: req.query.q?.trim() || null
    };
    const hasFilters = hasActiveFilterValues(filters);
    if (!hasFilters) {
      const cached = getCache('externalIds');
      if (cached) return res.json({ success: true, data: cached });
    }
    let query = supabase.from('JobOffers').select('ExternalId').not('ExternalId', 'is', null).neq('ExternalId', '');
    query = applyOfferFilters(query, req, filters);
    const { data, error } = await query;
    if (error) throw error;
    const externalIds = [...new Set((data || []).map(r => r.ExternalId).filter(Boolean))].sort();
    if (!hasFilters) setCache('externalIds', externalIds);
    res.json({ success: true, data: externalIds });
  } catch (error) {
    res.status(500).json({ success: false, error: 'Error interno del servidor', details: error.message });
  }
});

router.get('/job-offers/job-types', addUserToRequest, requireAuth, async (req, res) => {
  try {
    let query = supabase.from('JobOffers').select('JobType, ContractType').eq('Status', 'active');
    query = applyUserFilter(query, req);
    const { data, error } = await query;
    if (error) throw error;
    const types = [...new Set((data || []).flatMap(r => [r.JobType, r.ContractType]).filter(Boolean))].sort();
    res.json({ success: true, data: types });
  } catch (error) {
    res.status(500).json({ success: false, error: 'Error interno del servidor', details: error.message });
  }
});

router.get('/job-offers/companies', addUserToRequest, requireAuth, async (req, res) => {
  try {
    const filters = {
      status: normalizeStatus(req.query.status),
      locations: normalizeLocationFilter(req.query.location),
      sectors: normalizeStringFilter(req.query.sector),
      jobTitles: normalizeStringFilter(req.query.jobTitle || req.query.jobTitles),
      externalId: req.query.externalId && req.query.externalId !== 'all' ? String(req.query.externalId).trim() : null,
      search: req.query.q?.trim() || null
    };
    const hasFilters = hasActiveFilterValues(filters);
    if (!hasFilters) {
      const cached = getCache('companies');
      if (cached) return res.json({ success: true, data: cached });
    }
    let query = supabase.from('JobOffers').select('CompanyName').not('CompanyName', 'is', null).neq('CompanyName', '');
    query = applyOfferFilters(query, req, filters);
    const { data, error } = await query;
    if (error) throw error;
    const companies = [...new Set((data || []).map(r => r.CompanyName).filter(Boolean))].sort();
    if (!hasFilters) setCache('companies', companies);
    res.json({ success: true, data: companies });
  } catch (error) {
    res.status(500).json({ success: false, error: 'Error interno del servidor', details: error.message });
  }
});

router.get('/job-offers', addUserToRequest, requireAuth, async (req, res) => {
  try {
    const {
      q: search,
      status,
      location,
      sector,
      company,
      externalId,
      sortBy = 'CreatedAt',
      sortOrder = 'DESC',
      limit = 20,
      page = 1
    } = req.query;

    const validatedLimit = Math.min(Math.max(parseInt(limit) || 20, 1), 100);
    const validatedPage = Math.max(parseInt(page) || 1, 1);
    const offset = (validatedPage - 1) * validatedLimit;
    const filters = {
      search: search?.trim() || null,
      status: normalizeStatus(status),
      locations: normalizeLocationFilter(location),
      sector: sector && sector !== 'all' ? String(sector).trim() : null,
      company: company && company !== 'all' ? String(company).trim() : null,
      externalId: externalId && externalId !== 'all' ? String(externalId).trim() : null
    };

    let countQ = applyOfferFilters(supabase.from('JobOffers').select('Id', { count: 'exact', head: true }), req, filters);
    const { count, error: countError } = await countQ;
    if (countError) throw countError;
    const total = count || 0;

    if (total === 0) {
      return res.json(emptyState(validatedPage, validatedLimit, {
        search: filters.search,
        status: filters.status || 'all',
        location: filters.locations.length > 0 ? filters.locations : 'all',
        sector: filters.sector || 'all',
        externalId: filters.externalId || 'all'
      }));
    }

    const allowedSortFields = { CreatedAt: 'CreatedAt', Title: 'Title', CompanyName: 'CompanyName', Status: 'Status', StatusId: 'Status', PublicationDate: 'PublicationDate' };
    const validSortBy = allowedSortFields[sortBy] || 'CreatedAt';
    const ascending = String(sortOrder).toUpperCase() === 'ASC';
    const selectFields = 'Id, ExternalId, Title, DescriptionHtml, DescriptionText, CompanyName, Sector, Category, City, Region, SalaryRaw, SalaryMin, SalaryMax, JobType, ContractType, PublicationDate, CreatedAt, Status, Vacancies';

    let dataQ = applyOfferFilters(supabase.from('JobOffers').select(selectFields), req, filters);
    dataQ = dataQ.order(validSortBy, { ascending }).order('Id', { ascending: false }).range(offset, offset + validatedLimit - 1);
    const { data, error: dataError } = await dataQ;
    if (dataError) throw dataError;
    const offers = (data || []).map(mapOffer);

    const statsBase = () => applyUserFilter(supabase.from('JobOffers').select('Id', { count: 'exact', head: true }), req);
    const [statTotal, statActive, statDraft, statPaused] = await Promise.all([
      statsBase(),
      statsBase().eq('Status', 'active'),
      statsBase().eq('Status', 'draft'),
      statsBase().eq('Status', 'paused')
    ]);

    const hasMore = offset + offers.length < total;
    const lastOffer = offers.length > 0 ? offers[offers.length - 1] : null;
    const nextCursor = hasMore && lastOffer ? { lastCreatedAt: lastOffer.CreatedAt, lastId: lastOffer.id } : null;

    res.json({
      success: true,
      data: offers,
      items: offers,
      hasMore,
      total,
      next: nextCursor,
      pagination: {
        page: validatedPage,
        limit: validatedLimit,
        total,
        pages: Math.ceil(total / validatedLimit),
        hasMore,
        lastCreatedAt: nextCursor?.lastCreatedAt || null,
        lastId: nextCursor?.lastId || null
      },
      stats: {
        totalOffers: statTotal.count || 0,
        activeOffers: statActive.count || 0,
        pendingOffers: statDraft.count || 0,
        pausedOffers: statPaused.count || 0,
        totalSectors: 0,
        totalCities: 0
      },
      filters: {
        search: filters.search,
        status: filters.status || 'all',
        location: filters.locations.length > 0 ? filters.locations : 'all',
        sector: filters.sector || 'all',
        externalId: filters.externalId || 'all'
      }
    });
  } catch (error) {
    console.error('❌ Error listando ofertas:', error.message);
    res.status(500).json({ success: false, error: 'Error interno del servidor', details: error.message });
  }
});

router.put('/job-offers/:id/status', addUserToRequest, requireAuth, async (req, res) => {
  try {
    const offerId = parseInt(req.params.id);
    const nextStatus = normalizeStatus(req.body.status);
    if (!offerId || !nextStatus) return res.status(400).json({ success: false, error: 'ID o estado inválido' });

    let checkQ = supabase.from('JobOffers').select('Id, Title, Status').eq('Id', offerId);
    checkQ = applyUserFilter(checkQ, req);
    const { data: found, error: checkError } = await checkQ.limit(1);
    if (checkError) throw checkError;
    if (!found || found.length === 0) return res.status(404).json({ success: false, error: 'Oferta no encontrada' });

    const current = found[0];
    const { error } = await supabase.from('JobOffers').update({ Status: nextStatus, UpdatedAt: new Date().toISOString() }).eq('Id', offerId);
    if (error) throw error;

    res.json({
      success: true,
      message: `Oferta "${current.Title}" actualizada correctamente`,
      data: { id: offerId, previousStatus: current.Status, newStatus: nextStatus, newStatusId: statusId(nextStatus), title: current.Title }
    });
  } catch (error) {
    res.status(500).json({ success: false, error: 'Error interno del servidor', details: error.message });
  }
});

router.post('/job-offers', addUserToRequest, requireAuth, async (req, res) => {
  try {
    const body = req.body || {};
    const insertData = {
      UserId: isSuperAdmin(req) && body.UserId ? body.UserId : req.userId,
      ConnectionId: body.ConnectionId || body.connectionId || null,
      ExternalId: body.ExternalId || body.externalId || null,
      SourceSystem: body.SourceSystem || body.sourceSystem || null,
      Title: body.Title || body.title,
      DescriptionHtml: body.DescriptionHtml || body.Description || body.description || null,
      DescriptionText: body.DescriptionText || null,
      ApplicationUrl: body.ApplicationUrl || body.applicationUrl || null,
      ExternalUrl: body.ExternalUrl || body.url || null,
      CompanyName: body.CompanyName || body.company || null,
      CompanyExternalId: body.CompanyExternalId || body.companyId || null,
      CompanyLogoUrl: body.CompanyLogoUrl || body.companyLogoUrl || null,
      Country: body.Country || body.country || null,
      CountryCode: body.CountryCode || body.countryCode || null,
      Region: body.Region || body.region || null,
      City: body.City || body.city || null,
      Postcode: body.Postcode || body.postcode || null,
      Sector: body.Sector || body.sector || body.Category || body.category || null,
      Category: body.Category || body.category || null,
      Subcategory: body.Subcategory || body.subcategory || null,
      JobType: body.JobType || body.jobType || null,
      SalaryRaw: body.SalaryRaw || body.salary || null,
      SalaryMin: body.SalaryMin || null,
      SalaryMax: body.SalaryMax || null,
      Vacancies: body.Vacancies || body.vacancies || 1,
      PublicationDate: body.PublicationDate ? new Date(body.PublicationDate).toISOString() : null,
      Status: normalizeStatus(body.Status || body.status) || 'active',
      CreatedAt: new Date().toISOString(),
      UpdatedAt: new Date().toISOString()
    };
    if (!insertData.Title) return res.status(400).json({ success: false, error: 'Title es requerido' });

    const { data, error } = await supabase.from('JobOffers').insert(insertData).select().single();
    if (error) throw error;
    res.status(201).json({ success: true, data: mapOffer(data), message: 'Oferta creada correctamente' });
  } catch (error) {
    res.status(500).json({ success: false, error: 'Failed to insert job offer', details: error.message });
  }
});

module.exports = router;
